name: example CI_workflow
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: create an issue of failure
        if: always()
        uses: octokit/request-action@v2.1.9
        with:
          route: POST /repos/bholebaba0135/${{github.repository}}/Issues
          title: "Test failed: ${{github.ref}}"
          body: "A test failed. Please check"
        env:
          GITHUB_TOKEN: ${{secrets.PRACTICE_TOKEN}}
