name: example CI_workflow
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: create an issue of failure
        if: failure()
        uses: octokit/request-action@v2.4.0
        with:
          route: POST repos/${{github.repository}}/issues
          title: "Test failed: ${{github.ref}}"
          body: "A test failed. Please check"
        env:
          GITHUB_TOKEN: ${{secrets.PRACTICE_TOKEN}}
